### PR TITLE
feat: draft autowidget

### PR DESCRIPTION
**Pull request by jokasimr**
Related to #28 

Experiment with `AutoWidget` helper to make writing widgets for parameters a bit easier.

The `AutoWidget` class creates a composite widget from a constructor and a range of argument widgets.
The resulting widget is a simple form that produces a value of the constructor type.

### CODE REVIEW

**Comment by jokasimr** [comment]
Not sure how far we can get with this approach or a similar one, but to avoid having to create lots of very similar widgets for different workflow parameters it would be nice to automate what we can

**Comment by SimonHeybrock** [comment]
> but to avoid having to create lots of very similar widgets for different workflow parameters

Can you clarify your concern? I didn't think there would be too many different widgets.

**Comment by jokasimr** [comment]
There's some bookkeeping involved in making a widget that creates a composite value from a number of underlying basic widgets. It's good if we can avoid repeating it unnecessarily.

In particular, the `AutoWidget` let's you observe the composite value, and it's updated when any of the underlying values change. That didn't happen in the old widget implementations. That makes it easier to compose widgets together.

There are other ways to achieve that, not sure if this is the best, but I found it to work quite well so far.

**Comment by jokasimr** [comment]
There's some bookkeeping involved in making a widget that creates a composite value from a number of underlying basic widgets. It's good if we can avoid repeating it unnecessarily.

In particular, the `AutoWidget` let's you observe the composite value, and it's updated when any of the underlying values change. That didn't happen in the old widget implementations. That makes it easier to compose widgets together.

There are other ways to achieve that, not sure if this is the best, but I found it to work quite well so far.

**Comment by jokasimr** [comment]
>  I didn't think there would be too many different widgets.

Not necessarily too many, I agree. I thought there would be more than there seems to be. It might be easier to just keep the widget implementations separate

**Comment by SimonHeybrock** [comment]
If I understood correctly during the standup we will not pursue this for now, may be revisited later?

**Pull request closed without merging**
